site_name: SpiraDocs
# site_url: https://mydomain.org/mysite

theme:
  name: material
  # custom_dir: custom_theme/
  favicon: https://spiradoc.inflectra.com/images/favicon.ico
  font:
    text: Nunito Sans
  logo: assets/logo.svg
  palette:
    primary: black

nav:
  - About:
      - "Introduction to Spira": "blog/index.md"
      - "Legal Notices": "blog/index2.md"

extra_css:
  - assets/style.css

plugins:
  - search
  - blog:
      archive: false

copyright: © Copyright 2006-2024 Inflectra Corporation, All Rights Reserved | en-US
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zilladeepak/spiradocs-clone
    - icon: fontawesome/brands/x-twitter
      link: None
    - icon: fontawesome/brands/linkedin
      link: None
