site_name: SpiraDocs
site_url: https://mydomain.org/mysite

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  favicon: https://spiradoc.inflectra.com/images/favicon.ico
  font:
    text: Nunito Sans
  logo: assets/logo.svg
  palette:
    primary: black
    accent: amber

nav:
  - User Manual:
      - How to Use This Manual: "articles/UserManual/Manual.md"
      - Application Overview and Tips: "articles/UserManual/FunctionalityOverview.md"
      # - Common Elements Across the Application: none
      # - User Management: none
      - Products:
          - Homepage: "articles/UserManual/Products/Homepage.md"
          - Planning: "articles/UserManual/Products/Planning.md"
          - Testing: "articles/UserManual/Products/Testing.md"
          # - Developing: none
          # - Tracking: none
          # - Reporting: none
      # - Programs:
      #     - Homepage: none
      #     - Products: none
      #     - Capabilities: none
      #     - Program Milestones: none
      #     - Releases: none
      #     - Planning Board: none
      #     - Incident: none
      #     - Reporting: none
      # - Portfolio Homepage: none
      # - Enterprise Homepage: none
      - Mobile Access: "articles/UserManual/MobileAccess.md"
      - Keyboard Shortcuts: "articles/UserManual/KeyboardShortcuts.md"
  - About:
      - Introduction to Spira: "articles/About/Intro.md"
      - Legal Notices: "articles/About/Legal.md"

extra_css:
  - assets/style.css

plugins:
  - search
  - offline
  - print-site

copyright: © Copyright 2006-2024 Inflectra Corporation, All Rights Reserved | en-US
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

repo_url: https://www.inflectra.com/
repo_name: Inflectra

site_name: SpiraDocs
site_url: https://mydomain.org/mysite

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  favicon: https://spiradoc.inflectra.com/images/favicon.ico
  font:
    text: Nunito Sans
  logo: assets/logo.svg
  palette:
    primary: black
    accent: amber

nav:
  - User Manual:
      - How to Use This Manual: "articles/UserManual/Manual.md"
      - Application Overview and Tips: "articles/UserManual/FunctionalityOverview.md"
      # - Common Elements Across the Application: none
      # - User Management: none
      - Products:
          - Homepage: "articles/UserManual/Products/Homepage.md"
          - Planning: "articles/UserManual/Products/Planning.md"
          - Testing: "articles/UserManual/Products/Testing.md"
          # - Developing: none
          # - Tracking: none
          # - Reporting: none
      # - Programs:
      #     - Homepage: none
      #     - Products: none
      #     - Capabilities: none
      #     - Program Milestones: none
      #     - Releases: none
      #     - Planning Board: none
      #     - Incident: none
      #     - Reporting: none
      # - Portfolio Homepage: none
      # - Enterprise Homepage: none
      - Mobile Access: "articles/UserManual/MobileAccess.md"
      - Keyboard Shortcuts: "articles/UserManual/KeyboardShortcuts.md"
  - About:
      - Introduction to Spira: "articles/About/Intro.md"
      - Legal Notices: "articles/About/Legal.md"

extra_css:
  - assets/style.css

plugins:
  - search
  - offline
  - print-site
  # - blog:
  #     archive: false

copyright: © Copyright 2006-2024 Inflectra Corporation, All Rights Reserved | en-US
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables:

repo_url: https://www.inflectra.com/
repo_name: Inflectra


